version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    groups:
      backend-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
      day: "thursday"
    groups:
      frontend-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    groups:
      ci-dependencies:
        patterns:
          - "*"
