include = [".taplo.toml", "driver-db/*.toml"]

[formatting]
indent_string = "    "

[[rule]]
include = ["driver-db/*.toml"]

[rule.schema]
path = "driver-db-schema.json"

[rule.formatting]
reorder_arrays = true
reorder_keys = true
