services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: krgjlhaserjkgtnksngh
    ports:
      - "127.0.0.1:4321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: