manifest_version = "0.0.1"

[meta]
categories = ["Analog::ADC", "Sensor::PowerMeter"]
datasheets = ["https://ti.com/lit/gpn/INA219"]
manufacturer = "TI"
names = ["ina219"]
part_numbers = [
    "INA219AIDCNR",
    "INA219AIDCNR",
    "INA219AIDCNR",
    "INA219AIDCNR",
    "INA219AIDCNT",
    "INA219AIDCNT",
    "INA219AIDCNT",
    "INA219AIDCNT",
    "INA219AIDR",
    "INA219AIDR",
    "INA219BIDCNR",
    "INA219BIDCNR",
    "INA219BIDCNR",
    "INA219BIDCNR",
    "INA219BIDCNT",
    "INA219BIDCNT",
    "INA219BIDCNT",
    "INA219BIDCNT",
    "INA219BIDR",
    "INA219BIDR",
]

kicad_symbol = [
    "Sensor_Energy::INA219AxD",
    "Sensor_Energy::INA219AxDCN",
    "Sensor_Energy::INA219BxD",
    "Sensor_Energy::INA219BxDCN",
]
packages = ["SOIC-8", "SOT-23"]

[[dev_boards]]
connections = ["StemmaQt"]
link = "https://www.adafruit.com/product/904"
manufacturer = "Adafruit"
name = "INA219 High Side DC Current Sensor Breakout - 26V ±3.2A Max - STEMMA QT"

[interfaces.i2c]
addrs = [
    0x40,
    0x41,
    0x42,
    0x43,
    0x44,
    0x45,
    0x46,
    0x47,
    0x48,
    0x49,
    0x4a,
    0x4b,
    0x4c,
    0x4d,
    0x4e,
    0x4f,
]
interrupt = false
