# TODO: This is mock data! Check before using!
manifest_version = "0.0.1"

[meta]
names = ["lsm303agr"]
manufacturer = "ST"
datasheets = ["https://www.st.com/resource/en/datasheet/lsm303agr.pdf"]
categories = ["Sensor::Accelerometer", "Sensor::Magnetometer"]
part_numbers = ["LSM303AGRTR", "LSM303AGRLTR"]

packages = ["LGA-14"]

[dev_boards]
adafruit = 4413
mikroe = 2684
other = [{ name = "BBC micro:bit v2", link = "https://tech.microbit.org/hardware/" }]

[interfaces.i2c]
addrs = [0x1E, 0x1D]
interrupt = true
