manifest_version = "0.0.1"

[meta]
categories = ["Display::OLED"]
datasheets = ["https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf"]
kicad_symbol = []
manufacturer = "SolomonSystech"
names = ["SSD1306"]
packages = []
part_numbers = ["SSD1306"]

[[dev_boards]]
connections = ["StemmaQt"]
link = "https://www.adafruit.com/product/938"
manufacturer = "Adafruit"
name = "Monochrome 1.3\" 128x64 OLED graphic display - STEMMA QT / Qwiic"
